# This is actually running with python :DD
Program('program', Glob('*.cpp'))

# Note that Glob does not recurse -- that is it will only fetch
# the cpp files in the current directory (the one that the scons file is currently in)